# JJB (대추) Detection 설정
product: jjb
model: yolo11l  # yolo11l.pt 사전학습 모델
data_version: v9

training:
  epochs: 300
  batch: 32
  patience: 100
  dropout: 0.14
  iou: 0.35
  lr0: 0.00005
  lrf: 0.000001

prediction:
  conf: 0.5
