# WLN (호두) Classification 설정
product: wln
model: yolo11s-cls  # yolo11s-cls.pt 분류 사전학습 모델
data_version: v1

training:
  epochs: 300
  batch: 256
  patience: 50
  imgsz: 224
  lr0: 0.0005
  lrf: 0.00001
  optimizer: AdamW
  dropout: 0.3
  iou: 0.5

prediction:
  save: true
  save_txt: true
